"""Initial migration

Revision ID: 50b9728e2168
Revises: 
Create Date: 2025-07-26 21:02:15.110578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50b9728e2168'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('adminPassword', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_number')
    )
    op.create_table('robot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_robot_name_per_team')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=300), nullable=True),
    sa.Column('cad_format', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'name', name='uq_machine_name_per_robot')
    )
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assembly_url', sa.String(length=500), nullable=True),
    sa.Column('partstudio_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('access_key', sa.String(length=200), nullable=True),
    sa.Column('secret_key', sa.String(length=200), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('bom_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'name', name='uq_system_name_per_robot')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    op.drop_table('machine')
    op.drop_table('robot')
    op.drop_table('team')
    # ### end Alembic commands ###
