"""Initial

Revision ID: af711723c854
Revises: 
Create Date: 2025-07-28 00:20:45.179057

"""
from alembic import op
from sqlalchemy import Text
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af711723c854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assembly_url', sa.String(length=500), nullable=False),
    sa.Column('partstudio_urls', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('onshape_access_key', sa.String(length=100), nullable=False),
    sa.Column('onshape_secret_key', sa.String(length=100), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    # ### end Alembic commands ###
